### ISSUE TITLE
Function framework doesn't load env from .env.yaml file

### ISSUE THREAD

**Issue by mehedimi** [GoogleCloudPlatform/functions-framework-nodejs#116]
When I test my cloud function from the local machine using function-framework, It doesn't load the env variables from .env.yaml file.

Any suggestions?

**Comment by grant** [comment]
Hi @mehedimi,
The `.env.yaml` feature you're mentioning is the feature of the `gcloud` CLI. The Functions Framework is separate from that tool and uses normal env variables from your bash environment.

If we want to use yaml files for configuration with the Functions Framework, we need to use a yaml to env var converter.

Maybe this library would help if we want to convert yaml to env vars:
https://github.com/philnash/envyable

**Comment by mehedimi** [comment]
@grant  Thank's

**Comment by whyboris** [comment]
I created a tool precisely because of this pain point (with testing _Cloud Functions_ locally :trollface: )

[YAML-env-CLI](https://github.com/whyboris/YAML-env-CLI) lets you load all the `.yaml` environment variables right before launching the _functions-framework_ 🚀 

Install the [npm package](https://www.npmjs.com/package/yaml-env-cli):

```sh
npm install -g yaml-env-cli
```

and then in your start script, to load `staging.yaml` (for example), prepend the `yec` command:
```sh
export yec `staging.yaml` && functions-framework --target=helloWorld
```

All the _CLI_ does is convet the `.yaml` into a string that the _terminal_ `export` statement can use to load as environment variables 🚀
