### ISSUE TITLE
Support for other web frameworks?

### ISSUE THREAD

**Issue by dkolba** [GoogleCloudPlatform/functions-framework-nodejs#14]
There's a hard dependency on express.
Is support for other web frameworks like hapi.js planned?

**Comment by stew-r** [comment]
This is not currently planned. What's the use case for using hapi.js instead of Express?

**Comment by dkolba** [comment]
@stew-r hapi.js is 100% promisified so you can naturally async/await everything. Routing and middleware architecture is also way more sophisticated. @hueniverse will you help me out here?

**Comment by stew-r** [comment]
That sounds pretty neat! Unfortunately, we don't have immediate plans to provide another Node.js framework based on an alternative web framework.

That said -- the framework is pretty straightforward and we provide a permissive license. If you want to take a shot at implementing your own framework, I'd love to see it!

**Comment by hueniverse** [comment]
@stew-r the reason not to use express is that it's based on outdated architecture that's no longer how anyone should be building JS applications. The middleware architecture is all about callbacks and is completely incompatible with proper async/await design. I am not saying you should use hapi, but that using express is a mistake for any new project.

@dkolba not sure what you mean by "help" ;-). I am happy to explain the benefits of choosing another framework as the foundation of any new HTTP based project. I have plans to natively support setups like Google Functions and AWS Lambda in hapi as part of a roadmap this year of decoupling HTTP and allowing other transports/hosts. I expect AWS to be the first because of where existing hapi users needs are and my limited resources at the moment. This might change based on the needs of the companies paying for commercial licenses (enterprise customers will get priority...).

@stew-r would be happy to help/support any effort using hapi instead of express...

**Comment by stew-r** [comment]
Thanks for following up. To be clear: this isn't a completely new project. We're largely open sourcing (and improving) a component of the Cloud Functions codebase that has been around since the start. At this point, we don't have plans to re-base this runtime on an alternative web framework.

**Comment by QuantumInformation** [comment]
Nice work guys, I came here from trying to play with the Serverless framework, but glad Google are focused on this.
