### ISSUE TITLE
What is the difference between Functions Framework and Cloud Functions Emulator?

### ISSUE THREAD

**Issue by mishushakov** [GoogleCloudPlatform/functions-framework-nodejs#21]

**Comment by grant** [comment]
As stated in the README:
> The Node.js 10 runtime on Google Cloud Functions is based on the Functions Framework. On Cloud Functions, the Functions Framework is completely optional: if you don't add it to your package.json, it will be installed automatically.

The Emulator tries to mimic this logic but is completely separate from the runtime that is used by Cloud Functions.

**Comment by stew-r** [comment]
Grant is right. The Functions Framework is actually used in the Cloud Functions product whereas the Emulator is not. From a local development perspective, they both serve similar purposes though the Framework is explicitly not an emulator. It just includes a web server that you can run locally to bootstrap your function during local development. This same web server is used to run your function in the deployed Cloud Functions environment.

**Comment by mishushakov** [comment]
Ok, that's reasonable. But, still I don't understand the purpose of the project. What problem does Functions Framework actually solve? It's just express server, which requires a user-defined handler. Why do I need this project at all then, when I can set up my own express server with my handler, build a Docker Image from it and run it on my Kubernetes cluster? How can you refer to it as a FaaS anyways, because it can't serve non-nodejs workloads and doesn't have anything to do with the function lifecycle (like building the function, load balancing, proxying, metrics, etc.), which other providers like OpenFaaS or OpenWhisk have?

**Comment by stew-r** [comment]
Great questions.

> Ok, that's reasonable. But, still I don't understand the purpose of the project. What problem does Functions Framework actually solve? It's just express server, which requires a user-defined handler. Why do I need this project at all then, when I can set up my own express server with my handler, build a Docker Image from it and run it on my Kubernetes cluster?

You can absolutely do all of this yourself. But do you want to? You can also handle HTTP payloads directly but you prefer to use a web framework like Express because it frees you from having to think about the details and edge cases. As a developer, you can deliver more value to your project/business by building solutions to your problems than by thinking about handling HTTP, routing, etc.

The main idea with this framework is that (1) you can easily move your functions between different Knative environments (e.g., Cloud Run, Cloud Run on GKE, Knative installed in your own cluster, Knative installed in another provider's cluster). And you can do all of that without having to write an HTTP server.

> How can you refer to it as a FaaS anyways, because it can't serve non-nodejs workloads and doesn't have anything to do with the function lifecycle (like building the function, load balancing, proxying, metrics, etc.), which other providers like OpenFaaS or OpenWhisk have?

We're working on Functions Frameworks to support other languages.

Load balancing, proxying, metrics, etc. are interesting because some of that can be achieved via a framework. Other parts are directly related to the infrastructure/environment in which you run your function. Clearly, those can't simply be delivered via an `npm`-installable package.

**Comment by mishushakov** [comment]
Alright, questions solved. I guess, the real need for this express overlay, is just for Google to add some middleware (like logging layer or billing) on top. The idea with removing structures like routing, handling etc. sounds cool and sure, removing some responsibilities and headaches, but at the end of the day, you end up loosing a lot of flexibility and potential, which your own setup could provide to you (like defining a custom service-wide handler for authorisation before each request). That's by the way, what's Yandex is doing with its FaaS (not yet available for public). You can not only build, upload and run the functions, but also structure in which order they are triggered and schedule them like cron-jobs or Pub/Sub.

Do you think, there will be implementations for other framework as well, or a functionality to define a version of a framework? Express may fit for everyone, but personally I don't want each of my microservices to consume over 50 MB of dependencies, just for framework alone. And there is also room for security-concerns, since there are a lot of stuff in express. I think OpenFaas solves the problems perfectly with it's templates.

Thanks.

**Comment by stew-r** [comment]
This is a good discussion and I think it gets to the core of "why would I use functions as a service when I can get more control/flexibility/etc. by building it myself?" From the Cloud Functions perspective, we think that we can create a compelling offering that allows you to focus only on the problem you're trying to solve. We abstract away boilerplate, infrastructure management and common maintenance tasks so that you can maximize the impact of your engineering efforts.

To get this fully managed experience, you trade off some control. But we think that open source frameworks will allow you to regain some of that control. You can use this framework, add a Dockerfile and build a container -- this gives you more control than if you use Cloud Functions's fully managed experience. But you're now also responsible for what goes into that Dockerfile.

A couple of notes on your specific comments/questions:

> like defining a custom service-wide handler for authorisation before each request

We're working on better auth integration with Cloud Functions. Here again: we want to free you from having to write boilerplate to deal with auth in function code.

> structure in which order they are triggered

Yes, we occasionally hear this need from customers. We're actively looking into it.

> and schedule them like cron-jobs

You can do this today using [Cloud Scheduler and Pub/Sub](https://cloud.google.com/scheduler/docs/tut-pub-sub). Cloud Scheduler is a great way to run cron jobs in the cloud.

> Do you think, there will be implementations for other framework as well, or a functionality to define a version of a framework? Express may fit for everyone, but personally I don't want each of my microservices to consume over 50 MB of dependencies, just for framework alone. And there is also room for security-concerns, since there are a lot of stuff in express.

There's definitely a trade-off in choosing a framework like Express (e.g., it contributes to your microservice's size). But it also gives you the richness of Express's HTTP handling, middleware, etc. semantics. We aren't planning to create a second Node.js framework. There will be frameworks for other programming languages.

**Comment by Rotorsoft** [comment]
Hi there. Any news on the auth integration? I’ve been trying to authenticate a GCP service account to invoke a cloud function using the official npm package google-auth-library with no luck. Any pointers are appreciated. Thanks!

**Comment by grant** [comment]
Hi @Rotorsoft, can you create a new issue regarding auth? It may be worth posting code too. Thanks.

**Comment by Rotorsoft** [comment]
Hi Grant. Thanks for your quick reply! Not sure this is an issue, it might be me not knowing how to authenticate service accounts when calling cloud functions, but I can explain how to reproduce it. If you feel it's an issue I can go ahead and create one.

Steps:

1. Follow README steps to create hello-world function - Works fine in local environment
2. Deployed function to cloud (nodejs10 http-trigger) but with limited access when asked. Once I look at the deployed resource, only the service account I have configured have permission to invoke the function
3. HTTP GET from my local PC (browser, postman, etc) gets 401 error ... that's what I expect
4. Created nodejs console app and installed google-auth-library, downloaded service account credentials (json file) and set env.GOOGLE_APPLICATION_CREDENTIALS= path
5. Following code shows how I'm trying to call the function and I'm still getting 401 errors

```javascript
const { GoogleAuth } = require('google-auth-library')

process.env.GOOGLE_APPLICATION_CREDENTIALS='./google_creds.json'

const test = async () => {
  const auth = new GoogleAuth()
  const client = await auth.getClient()
  console.log(client)
  const res = await client.request({ url: 'URL OF CLOUD FUNCTION HERE' })
  console.log(res)
}

test()
```
The client is resolving to a JWT instance as expected, but the response is again a 401

```html
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 Unauthorized</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Unauthorized</h1>
<h2>Your client does not have permission to the requested URL <code>/hello</code>.</h2>
<h2></h2>
</body></html>
```
Seems like the JWT token is invalid. I was expecting to call my hosted cloud functions the same way I call other google apis where the authentication is automatically resolved when I'm working locally.

Please let me know your thoughts.

Thanks again!
