### ISSUE TITLE
Binaries should have language-specific alias

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/functions-framework-nodejs#225]
The Node.js FF can be invoked via a system-wide binary if it is installed with `npm install -g`.

This is fine for environments where only one FF is installed, but environments with multiple FFs (i.e. FFs for multiple languages on the same machine, or multiple FF versions for a single language) make it harder to select specific FFs.

See [this issue](https://github.com/GoogleCloudPlatform/functions-framework/issues/38) for more context.

**Comment by hdp617** [comment]
There's a Node.js specific alias i.e. `functions-framework-nodejs` in [0]. Is this what you're referring too? Please reopen the issue if you it's not.

[0] https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/1ca74aee74cdc803cba90721d98fffbf2db3ab60/package.json#L33

**Comment by ace-n** [comment]
Yes - though I'd argue we could do a better job documenting this.

**Comment by grant** [comment]
Hey Ace, I don't think we can apply the logic you've suggested of a -LANG postfix to every framework.

We shouldn't encourage folks to install the alias `functions-framework` globally. The quickstart has clear instructions on how to the `functions-framework` (or now `functions-framework-nodejs`) binary that is only scoped to a package, not globally.

Thus there shouldn't be any mixups between ffs.

**Comment by ace-n** [comment]
That's fair - I guess the question here becomes
> Do we _allow_ users to "shoot themselves in the foot", at the expense of additional complexity and/or documentation?

I'm in favor of saying "no". I recognize this may differ between languages though, so I'm curious to see what someone like @bcoe might say.

(Alternatively - could we convince NPM to [address this issue](https://stackoverflow.com/questions/40068151/preventing-global-installations-of-an-npm-package) and allow `WARN`s on global package installs?)

**Comment by grant** [comment]
I haven't seen a user have an issue with the binary. I don't think there is any foot shooting because Node developers understand how `bin` works or don't have to if they just follow the instructions.

We really don't want people to install _globally_ so we don't document that. If they do that, they should understand how Node works. Like https://docs.npmjs.com/files/package.json#bin

If we want to, we can put a sentence under https://github.com/GoogleCloudPlatform/functions-framework-nodejs#installation saying you can now use `npx @google-cloud/functions-framework` to start the package, but I think that's overkill since we already say that.

---

I don't recommend `-g` so I don't know what suggestion you're making for the README. Can you suggest a change?

**Comment by ace-n** [comment]
Perhaps the right move is to close this issue + ping NPM themselves, but I'd like @bcoe to verify that before doing so.

**Comment by ace-n** [comment]
Verified with @bcoe offline; closing.
