### ISSUE TITLE
Cannot deploy functions using firebase-admin and ADC via firebase-tools

### ISSUE THREAD

**Issue by iwata** [GoogleCloudPlatform/functions-framework-nodejs#25]
I tried to upgrade Node v8 to v10.
But, it occurred these errors and failed to deploy via firebase-tools version 3.8.0.

```
Function failed on loading user code. Error message: Warning, FIREBASE_CONFIG environment variable is missing. Initializing firebase-admin will fail
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (/srv/functions/lib/index.js:30:47)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.getUserFunction (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:57:32)
    at Object.<anonymous> (/srv/node_modules/@google-cloud/functions-framework/build/src/index.js:49:33)
Could not load the function, shutting down.
```

I re-tried with setting FIREBASE_CONFIG, but the result did not change, and the same error was output.
Here is my initialization code.

```typescript
import * as admin from 'firebase-admin'
admin.initializeApp()
```

**Comment by thechenky** [comment]
Hi @iwata thanks for the report! This is a known bug - we have a fix submitted and it should hopefully roll out next week. The reason this is happening is because Node 10 runtime was not pulling in hidden files like `.runtimeconfig.json` which the Firebase SDKs need to automatically set env variables like `FIREBASE_CONFIG`. I'd like to point out, however, that you still need to deploy with Firebase CLI in order to have that config set - otherwise you will need to initialize admin with the needed parameters (see these [docs](https://firebase.google.com/docs/admin/setup#initialize_the_sdk) for more info).

This issue is explained in more detail in https://github.com/firebase/firebase-functions/issues/433 and https://github.com/firebase/firebase-functions/issues/432.

**Comment by jthegedus** [comment]
@thechenky Wait a minute, is the implication here that we can use the `functions-framework` to write functions to be deployed to Firebase via the `firebase-tools` CLI?

**Comment by grant** [comment]
As @thechenky mentioned, this is a known bug with Firebase repo (`firebase-tools`) and not this repo (`functions-framework`). Moving this issue as such.

**Comment by thechenky** [comment]
Sure, transferring.

**Comment by thechenky** [comment]
@grant I don't have permissions on this repo to transfer, can you try?

**Comment by grant** [comment]
Hey @iwata, this bug is with `firebase-tools@3.8.0` as you mentioned in the report.

Can you please file the issue in that repo?
https://github.com/firebase/firebase-tools

Closing this issue.

**Comment by iwata** [comment]
Thanks!
I created new issue.
https://github.com/firebase/firebase-tools/issues/1319
