### ISSUE TITLE
Putting limits on mem+CPU usage, to see actual function-like performance

### ISSUE THREAD

**Issue by braeden123** [GoogleCloudPlatform/functions-framework-nodejs#39]
Hey again,

Another quick feature request, not sure if this is feasible, or possible in project spec. But I'm having issues with functions executing fine on this environment, but not when deployed to GC.

Thanks!

**Comment by stew-r** [comment]
This is a great idea that you can achieve by building a Docker container. I don't think a Node.js package can provide this type of functionality. You could, e.g., do something like:

- write a Dockerfile
- build the container image
- [run the container image locally](https://cloud.google.com/run/docs/testing/local) using Docker. I think Docker supports flags that allow you to control CPU and Memory

Note that, even if you take these steps, you won't get a complete replica of the environment since, e.g., X MB of RAM on one architecture might perform differently than on another architecture.

**Comment by braeden123** [comment]
Thanks!

**Comment by stew-r** [comment]
@ace-n FYI good input for testing docs.

Rather than focus on unit/integration/system tests, "how do I run my function in a way that is similar to the deployed environment?" might be a better target for us to solve.
