### ISSUE TITLE
Target function name not parsed properly

### ISSUE THREAD

**Issue by nikita-fuchs** [GoogleCloudPlatform/functions-framework-nodejs#397]
As we're told to use[ something custom](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/38) than `--env-vars-file .env.prod.yaml` when testing cloud functions locally, I followed suit using `dotenv-cli`

The problem is that the target function is not recognised in that case, and it falls back to a default function value called `function`.

Example:

`npm run build && dotenv -e .env.staging npx functions-framework --target=api --source ./build/src/ --signature-type=http`
 gives

```
Serving function...
Function: function
Signature type: http
```

To get it working, I need to rename my exported function to `function`. When doing simply
`npm run build && npx functions-framework --target=api --source ./build/src/ --signature-type=http` , the `target` is being evaluated correctly.

**Comment by grant** [comment]
Hi @nikita-fuchs,

Can you provide more detailed instructions for how to reproduce this error?

I haven't used the `dotenv-cli` and am not sure if that works here.

Does it work without using that CLI and just specifying the `--target` normally?

**Comment by matthewrobertson** [comment]
@nikita-fuchs it sounds like  the `--target`, `--source` and `--signature-type` flags aren't actually being passed to the functions framework. I suspect this is because you haven't constructed your command correctly. I am not too familiar with dotenv-cli but it looks like this use case is described in the ["Flags to the underlying command" section of their docs](https://www.npmjs.com/package/dotenv-cli#user-content-flags-to-the-underlying-command)

> If you want to pass flags to the inner command use `--` after all the flags to `dotenv-cli`
