### ISSUE TITLE
Parsing body of requests without Content-Type header

### ISSUE THREAD

**Issue by ssttevee** [GoogleCloudPlatform/functions-framework-nodejs#99]
Is it expected behaviour that requests without a `Content-Type` header gets parsed as if it were `application/json`?

I'm trying to handle requests from a third party whose requests lack an explicit `Content-Type`. The request body should be hundreds of bytes long, but all I get from `req.body` is an empty object, lit. `{}`, and I don't see another way to access the raw body.

The same behaviour is observed on a published function.

**Comment by grant** [comment]
Hi @ssttevee, can you provide more specific details with this issue report? Example code?
We use Express' body-parser.

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/invoker.ts#L564

**Comment by ssttevee** [comment]
This is the function I used.

```js
export function hello(req, res) {
    console.log(req.method, req.url);
    console.log(req.headers);
    console.log(req.body);
    res.end();
}
```

This is the command I used to start the server.

```sh
functions-framework --target hello
```

Using curl to send data with no content type:

```
~ $ curl -v 'http://localhost:8080' -H 'content-type: ' --data hi
* Rebuilt URL to: http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 2
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Date: Fri, 20 Sep 2019 19:17:34 GMT
< Connection: keep-alive
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
```
POST /
{
  host: 'localhost:8080',
  'user-agent': 'curl/7.58.0',
  'content-length': '2',
  accept: '*/*',
  'x-forwarded-for': '::1',
  'accept-encoding': 'gzip'
}
{}
```
Using an arbitrary content type returns a buffer:
```
~ $ curl -v 'http://localhost:8080' -H 'content-type: arbitrary/type' --data hi
* Rebuilt URL to: http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> content-type: arbitrary/type
> Content-Length: 2
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Date: Fri, 20 Sep 2019 19:23:00 GMT
< Connection: keep-alive
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
```
POST /
{
  host: 'localhost:8080',
  'user-agent': 'curl/7.58.0',
  accept: '*/*',
  'content-type': 'arbitrary/type',
  'content-length': '2'
}
<Buffer 68 69>
```

**Comment by grant** [comment]
I think you'll find the same issue with Express/Express body-parser.
Can you try to reproduce the issue with Express?
https://github.com/expressjs/body-parser

**Comment by grant** [comment]
I've recommended filing a bug with body-parser.

Since this is a pretty rare case where the Content-Header isn't supplied, and there are no other cases, going to close.

**Comment by simwijs-evolante** [comment]
Experiencing the same problem. You should be able to customize the functions to parse the body yourself. Right now it leaves you hanging without a way to fix it, especially if you are dependent on a system you can't fix (since they for some reason don't set a content-type header, but you know how to parse it)

https://stackoverflow.com/questions/61365258/firebase-function-with-no-specific-content-type-returns-undefined-rawbody


A shame, since this works with AWS Lambda just fine (it works fine without a content-type, and sometimes even manages to parse the request without it)

Speaking from experience using the same systems integration where AWS Lambda works out of the box, but Cloud Functions leaves you without any way to deal with this problem. It would be helpful to be able to choose your own parser.
